### ISSUE TITLE
Importing from mirgecom forces call to MPI_Init (via mpi4py)

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#105]
Currently, `mpi4py.MPI` gets imported in mirgecom's [\_\_init\_\_.py](https://github.com/illinois-ceesd/mirgecom/blob/dc69fec5b7fabac2022ff4ddfa223a28d2ff947e/mirgecom/__init__.py#L30). As a result, importing anything from mirgecom will trigger an `MPI_Init`. For most uses this isn't really an issue, but it seems to be causing me some trouble in the context of parallel testing.

As is, when I try to launch MPI from inside a test in mirgecom, it fails (I get a non-zero exit code, and the command doesn't get executed). If I comment out the MPI stuff in \_\_init\_\_.py, it works fine. (This is with OpenMPI on my laptop.) I'm guessing it doesn't like running `mpiexec` from inside a process that has already initialized MPI?

Is there maybe a way we could tweak the code for that warning message (or put it somewhere else) so it doesn't always force an `MPI_Init` on import?

**Comment by matthiasdiener** [comment]
Instead of the code that is currently in `__init__.py`, maybe we could check if the mpi4py module has been loaded and only then evaluate `rank` and `size`. This might be a bit more complicated since the order in which the mpi4py/mirgecom modules are imported determines whether the warning is shown or not...

**Comment by majosm** [comment]
https://bitbucket.org/mpi4py/mpi4py/issues/85/manual-finalizing-and-initializing-mpi

This might be useful.

**Comment by majosm** [comment]
...or not. Two things:

1. I didn't realize that python modules are loaded only once per process (I guess I was thinking it was per-module or something along those lines) -- which means that if we use the trick in the link, we will get different behavior (i.e., needing to call `MPI_Init()` manually or not) depending on the order in which modules happen to get imported. I think that would apply to anything that imports mirgecom as well... so I suspect this is something we will want to avoid.
2. I was wrong about `python -m mpi4py ...` -- it does not actually call `MPI_Init()`. So we can't depend on that to help us either.

Rather than doing this in the top level of mirgecom, would there be a way to trigger this more locally (i.e., wherever the first thing that's impacted by `XDG_CACHE_HOME` is executed)? And then use the trick @matthiasdiener suggested with checking if `mpi4py.MPI` has already been imported?

Maybe we can talk about this at the meeting tomorrow -- I'll make a note.
