### ISSUE TITLE
CI runs twice on pull request update

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#144]
I just noticed that the CI runs twice when a pull request is updated ([example](https://github.com/illinois-ceesd/mirgecom/pull/128)). It looks like it's getting triggered for both the `push` and `pull_request` events.

I wonder if we should change the `push` event to apply only to master?

```diff
 on:
   pull_request:
   push:
+    branches:
+      - master
   schedule:
   - cron:  '5 0 * * *'
```

**Comment by matthiasdiener** [comment]
> I just noticed that the CI runs twice when a pull request is updated ([example](https://github.com/illinois-ceesd/mirgecom/pull/128)). It looks like it's getting triggered for both the `push` and `pull_request` events.
> 
> I wonder if we should change the `push` event to apply only to master?
> 
> ```diff
>  on:
>    pull_request:
>    push:
> +    branches:
> +      - master
>    schedule:
>    - cron:  '5 0 * * *'
> ```

Yeah, I think that makes sense.
