### ISSUE TITLE
Wave operator unstable, tests are not sufficient

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#15]
When trying to pull the sign changes from #6 into grudge, I discovered that

- [x] the modified operator is not stable (the upwind part of the flux also needs a sign flip), which revealed that
- [x] the tests as they are really aren't sufficient: we also need to check stability. The easiest way is probably to integrate for ~10 time steps and check that the solution stayed bounded.
- [x] While we're at it, I would like the wave equation test to assert that the solution (semi-symbolically) solves the wave equation (i.e. take derivatives symbolically, then numerically evaluate the residual, and observe that the result is floating point fuzz).
- [x] While we're at it (part 2), maybe merge the two (largely identical) wave tests to be one test parametrized on the solution.
- [ ] While we're at it (part 3), could you submit a PR into the `array-context` branch of grudge (if that hasn't yet been merged into master) that adds your sign fixes to `examples/wave/wave-eager*.py`?

**Comment by majosm** [comment]
How's #16 for WWAI part 2? Also handles part 1 indirectly, I think.

**Comment by inducer** [comment]
Looks pretty good. Left some comments.

**Comment by inducer** [comment]
Fixed by #22.
