### ISSUE TITLE
Verify compatibility with Numpy 1.20

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#170]
Changes that *might* cause us problems:

- https://numpy.org/devdocs/release/1.20.0-notes.html#isinstance-dtype-np-dtype-and-not-type-dtype-is-not-np-dtype
- https://numpy.org/devdocs/release/1.20.0-notes.html#numpy-scalars-are-cast-when-assigned-to-arrays
- https://numpy.org/devdocs/release/1.20.0-notes.html#array-coercion-restructure

Related:
- https://github.com/inducer/pytools/issues/54

@matthiasdiener Could you take a look?

**Comment by matthiasdiener** [comment]
According to #173, we seem to be fine, as long as we are running with the fixed pytools version. Could you make a new pytools release?

**Comment by inducer** [comment]
Thanks!

> Could you make a new pytools release?

https://pypi.org/project/pytools/2020.4.4/

**Comment by matthiasdiener** [comment]
> > Could you make a new pytools release?
> 
> https://pypi.org/project/pytools/2020.4.4/

That was quick ;-) Testing with the released version in #173.

**Comment by inducer** [comment]
(Now also in conda-forge)

**Comment by matthiasdiener** [comment]
> (Now also in conda-forge)

Seems to be working out of the box now. Let's come this issue (and #173)?

**Comment by inducer** [comment]
:+1: Thanks for doing the work to make sure we're OK!
