### ISSUE TITLE
Should run examples as part of CI

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#18]
cc @MTCam 

Created because #7 creates examples. (which is a good thing, but if nothing ensures they keep running, they won't)

[Example CI script](https://github.com/inducer/meshmode/blob/7826fa5e13854bf1dae425b4226865acc10ee01f/.github/workflows/ci.yml#L41-L54)

**Comment by MTCam** [comment]
I added a runner and a CI for running the example.  The example will fail if the solution diverges from the expected/exact solution.  In the next iteration I would like to add command line arguments to set which case to run, and other params.

**Comment by MTCam** [comment]
#55 adds examples running to CI for mirgecom
[This PR](https://github.com/illinois-ceesd/emirge/pull/68) adds examples running to CI for emirge

**Comment by matthiasdiener** [comment]
Isn't this done already?

**Comment by MTCam** [comment]
Examples run as a part of CI, for both mirgecom, and emrige.  That is, emirge CI runs mirgecom examples to verify correct installation.
