### ISSUE TITLE
Abort if multiple ranks are using the same GPU

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#190]
cc @matthiasdiener 

Context: Lrun bug found by @matthiasdiener

**Comment by matthiasdiener** [comment]
- Use bus ID

**Comment by matthiasdiener** [comment]
> * Use bus ID

Well, that won't work. Here is the complete list of bus and slot IDs of the 4 GPUs on a Lassen node:

```
[NV/0]    CL_DEVICE_PCI_BUS_ID_NV                         4
[NV/0]    CL_DEVICE_PCI_SLOT_ID_NV                        0

[NV/1]    CL_DEVICE_PCI_BUS_ID_NV                         5
[NV/1]    CL_DEVICE_PCI_SLOT_ID_NV                        0

[NV/2]    CL_DEVICE_PCI_BUS_ID_NV                         3
[NV/2]    CL_DEVICE_PCI_SLOT_ID_NV                        0

[NV/3]    CL_DEVICE_PCI_BUS_ID_NV                         4
[NV/3]    CL_DEVICE_PCI_SLOT_ID_NV                        0
```

😢

**Comment by inducer** [comment]
There is `cuDeviceGetUuid`.

https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__DEVICE.html#group__CUDA__DEVICE_1g987b46b884c101ed5be414ab4d9e60e4

**Comment by matthiasdiener** [comment]
> There is `cuDeviceGetUuid`.

Sure, but this function (as well as similar ones like `cuDeviceGetPCIBusId`) would break the API for the `cl_nv_device_attribute_query` extension, and might therefore not be acceptable for pocl. We could roll our own API (maybe in pyopencl?), but that also doesn't seem great.

**Comment by inducer** [comment]
I think it's worth a try to roll our own `CL_DEVICE_` constants. We can then negotiate with the pocl folks to see what they think. Worst case, we ship patched versions of pocl in conda forge. Best case, we submit them to Khronos.

**Comment by matthiasdiener** [comment]
First draft is here: https://github.com/pocl/pocl/pull/910
