### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#199]
Not sure what's up. https://github.com/illinois-ceesd/mirgecom/actions/runs/500037922 @matthiasdiener and I had been discussing a bit [here](https://github.com/illinois-ceesd/mirgecom/pull/198) already.

I'm also not sure why it didn't email me when the build first failed. Did any of you get an email?

cc @matthiasdiener @lukeolson @MTCam @majosm

**Comment by inducer** [comment]
I reran the meshmode CI, which uses an (AFAIK) pretty simlar setup, and that seems fine: https://github.com/inducer/meshmode/runs/1738320588

Grudge (rerun): https://github.com/inducer/grudge/runs/1645916477

**Comment by inducer** [comment]
#200

**Comment by lukeolson** [comment]
Nope, no email notification.
