### ISSUE TITLE
NANs with `python -O`

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#208]
This is a duplicate of [a potentially mis-placed issue](https://github.com/inducer/loopy/issues/208) against Loopy.

_MIRGE-Com_ appears to produce NANs almost immediately when runs are started with `python -O`. The issue occurs on current master branch out-of-the-box, and does not appear to be platform-specific.  To reproduce the issue, try these on master branch:
```
python -O -m mpi4py wave-eager-mpi.py (produces NANs)
python -m mpi4py wave-eager-mpi.py (runs normally)
```

At @matthiasdiener request, changing (loopy/loop/options.py) around line 213:
```
	            # Fails
                # skip_arg_checks=kwargs.get("skip_arg_checks", sys.flags.optimize),

	            # Works
                # skip_arg_checks=kwargs.get("skip_arg_checks", False),

	            # Fails
                skip_arg_checks=True,
```
Can toggle this failure on-and-off.

**Comment by inducer** [comment]
Likely fixed by https://github.com/inducer/loopy/pull/210 via https://github.com/inducer/loopy/pull/212. @MTCam, please speak up if not. Closing.

**Comment by MTCam** [comment]
Just now seeing this. It works!
