### ISSUE TITLE
Logging makes warnings re: units

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#215]
This may not be an actual issue, per se, but hopefully this will help center a conversation around some units and unit-handling for MIRGE-Com.

Currently, logging watches for built-in simulation quantities makes error messages like this:

```
/Users/mike/work/CEESD/MirgeCom/Drivers/CEESD-Shock1D/emirge/mirgecom/mirgecom/logging_quantities.py:289: UserWarning: Logging had to guess units for 'pressure': 'Pa'.It should not have to. Some other component should tell it.
  warn(f"Logging had to guess units for '{quantity}': '{unit}'."
```

We need a way to indicate to the logger what the units are for this and also for user-defined quantities of interest. 

This warning can be reproduced on `mirgecom@logging` by running the `vortex-mpi.py` example:
`python -m  mpi4py examples/vortex-mpi.py`

**Comment by matthiasdiener** [comment]
I think these are fixed in the most recent commits from today.

**Comment by inducer** [comment]
#96 should probably be marked to close this.
