### ISSUE TITLE
mirgecom.initializers documents underscored functions

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#230]
see https://github.com/illinois-ceesd/mirgecom/pull/226#discussion_r572192615

**Comment by majosm** [comment]
Is this referring to the

```python
.. automethod: _make_pulse
.. automethod: _make_uniform_flow
```

? (The link isn't jumping to the relevant part of the diff for me.)

**Comment by inducer** [comment]
(fixed the link, but I believe @MTCam is already on it.)
