### ISSUE TITLE
Need Pyro docs linked

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#234]
This is not a _MIRGE-Com_ issue, per se, but... would like to link [_Pyrometheus_](https://github.com/ecisneros8/pyrometheus/) documentation inside _MIRGE-Com_ docs.   

I think I've got a handle on the markup and config for doing this, but need to figure out how to generate net-accessible user-facing documentation for _Pyrometheus_ itself (preferably from my branch of it).  Can anyone help with this?

Thanks!

**Comment by matthiasdiener** [comment]
Can you clarify - isn't the documentation already available (https://pyrometheus.readthedocs.io/en/latest/)? 
Whoever is admin on that project can also add a build for your branch of pyrometheus.

**Comment by MTCam** [comment]
That's all i needed, thanks!   The main branch docs will do - it'll merge soon enough.
