### ISSUE TITLE
CI fails silently 

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#241]
I am sorry to report this:

CI is currently failing silently.  Turns out that papering over the memory issue (can be undone with #216) was a bad idea, or at least needs tweaking.  Looking down through the CI capture for `pytest` sections, I saw a failing test for CTI file reads, but a green checkmark on the CI dashboard.

The CTI file read issue appears to be fixed (by #239), so it is no longer a good example, unless we can dig up CI history on it.

The fix for CI may be as simple as #240, or similar. Either way, paper can only go so far and it is tearing.

**Comment by majosm** [comment]
[Here](https://github.com/illinois-ceesd/mirgecom/runs/1860379003?check_suite_focus=true) is the CI run with the failure.

**Comment by MTCam** [comment]
> [Here](https://github.com/illinois-ceesd/mirgecom/runs/1860379003?check_suite_focus=true) is the CI run with the failure.

Thanks @majosm! So far, so good (#240) catches the CTI error now. If #240 merges, then CI in master will begin to fail, and should be fixed by fixing the CTI read error with #239.
