### ISSUE TITLE
Checkpoint only shows temperature/pressure from rank 0

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#258]
While working on #257 today I noticed that the current checkpoint code only uses the temperature and pressure data from rank 0 when writing status information to stdout. This seems potentially misleading. Should it be doing reductions over the whole domain instead?

**Comment by MTCam** [comment]
Correct.  The original code which collected field statistics across all ranks was removed in favor of using the discretization's built-in norms.  It was my understanding that these norms would be extended on the inside to perform the parallel reductions.

This whole thing may be OBE after #96, as I think that facility may take over responsibility for doing runtime field data stats/reports.

**Comment by inducer** [comment]
Agree, #96 should take care of that. Since we don't need the same info reported twice, maybe we can make this issue about removing the old code?
