### ISSUE TITLE
Parallel runs often fail to spawn on Lassen

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#292]
This issue has presented itself on Lassen, and is pretty severe lately.

Upon spawning parallel jobs on lassen with something like:
> jsrun -g 1 -a 1 -n 32 python -O -u -m mpi4py nozzle.py

The job often fails during setup (before stepping) with this message:
`CUDA_ERROR_FILE_NOT_FOUND: file not found`

The error is typically hidden in several pages of output from grudge, meshmode, and loopy:
```
< ... pages of similar messages ... >
grudge_assign_0: preprocess done
grudge_assign_0: preprocess start
grudge_assign_0: preprocess done
CUDA_ERROR_FILE_NOT_FOUND: file not found
grudge_assign_0: preprocess start
grudge_assign_0: preprocess start
grudge_assign_0: preprocess start
< ... more similar messages ... >
ERROR:  One or more process (first noticed rank 3) terminated with signal 6
```

The issue is more troublesome at higher node counts.  For the example given above, the job had to be attempted 13 times before it finally ran properly without failing due to this message. 

For now, I just want to submit this issue in case someone has seen this, or has any ideas.  I do not know if the issue is limited to the Y1 Nozzle case (I can't imagine that it is), but I have not tested it for other cases.

**Comment by matthiasdiener** [comment]
Can you try setting `CUDA_CACHE_PATH` to something in `/tmp`? (cc: https://developer.nvidia.com/blog/cuda-pro-tip-understand-fat-binaries-jit-caching/)

**Comment by MTCam** [comment]
> Can you try setting `CUDA_CACHE_PATH` to something in `/tmp`? (cc: [developer.nvidia.com/blog/cuda-pro-tip-understand-fat-binaries-jit-caching](https://developer.nvidia.com/blog/cuda-pro-tip-understand-fat-binaries-jit-caching/))

Same issue.

**Comment by matthiasdiener** [comment]
Last chance: Can you try setting `POCL_CACHE_DIR` to `/tmp`?
