### ISSUE TITLE
CUDA performance regression LLVM9 -> LLVM11

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#295]
@nchristensen discovered that LLVM11 (when run from POCL 1.6) will inject `.pragma "nounroll";` into the PTX kernels it generates, while LLVM9 (also with POCL1.6) does not. He observed that this seems to impair performance compared to Nvidia CL. At this point, we don't know when or why this change (likely within LLVM) was applied.

Here's an example kernel: https://gist.github.com/inducer/be48fc907b44849b471aa3282696ea75

@nchristensen, if I missed any details, could you add them here?

cc @matthiasdiener @isuruf

**Comment by nchristensen** [comment]
For comparison, here is the PTX of the same kernel generated with POCL 1.6 using LLVM9 https://gitlab.tiker.net/tracking/nick/-/blob/602a1cec2b5bd5a15571c352ef6619e8e9796e79/other/pocl_elwise_linear_LLVM9.ptx

**Comment by inducer** [comment]
(It occurred to me that the Gitlab links are not public. I've copied the content to public gists and updated the links.)

**Comment by isuruf** [comment]
Can you post the OpenCL kernel too?

**Comment by nchristensen** [comment]
Sure. https://gist.github.com/nchristensen/522178639af94ff7308b4186ab4e1929

**Comment by matthiasdiener** [comment]
Do you have performance data comparing the two kernel versions?

**Comment by nchristensen** [comment]
The top figure is with LLVM 9 and the bottom image is with LLVM 11. Comparing the red and blue bars between the charts there is a consistent 50 to 80 GB/s increase in throughput moving from LLVM 11 to LLVM 9.

![image](https://user-images.githubusercontent.com/11543181/112410942-f5a41b80-8d13-11eb-8917-5884d311a2a8.png)

![image](https://user-images.githubusercontent.com/11543181/112410971-048ace00-8d14-11eb-8a2b-3493e4199cce.png)

**Comment by matthiasdiener** [comment]
Maybe some change in default unrolling thresholds (see e.g. https://github.com/llvm/llvm-project/commit/7acfda633f1378344efde22bfed242dd56c26cdd)? Note that apart from the unrolling pragma, the PTX code generated by LLVM9 seems to have been unrolled, while the LLVM11 PTX code seems to be not unrolled.

**Comment by isuruf** [comment]
Try passing `-mllvm -unroll-threshold=1000 -unroll-threshold-aggresive=1000` to clang. Not sure if there's a way to pass through OpenCL, but you can add it to https://github.com/pocl/pocl/blob/84d09d2a8a48265462adf3c07a649f8c3823d6d8/lib/CL/devices/cuda/pocl-cuda.c#L1694

**Comment by nchristensen** [comment]
Adding the flags didn't work but flipping cg.UnrollLoops to true [here](https://github.com/pocl/pocl/blob/4f3f90809c46d0277de8ef47c38a9dbae218837b/lib/CL/pocl_llvm_build.cc#L511) seems to re-enable unrolling. 

https://gist.github.com/nchristensen/1b8d9048b481d6c8f1879b982ccb15ce

**Comment by inducer** [comment]
> Adding the flags didn't work but flipping cg.UnrollLoops to true here seems to re-enable unrolling.

Nice find! Do you think we'll be able to patch pocl to not disable loop unrolling for the CUDA target?

**Comment by nchristensen** [comment]
With more investigation I believe flipping `cg.UnrollLoops` did not resolve the problem. I am also less certain about how the compiler version relates the whether or not loops are unrolled. After running tests of `elwise_linear` with different pocl and LLVM versions here is what I observe. 

LLVM 9 with Pocl 1.6 - Self-compiled - Always unrolls (496 GB/s)
LLVM 11 with Pocl 1.6 - Self-compiled - Always unrolls (499 GB/s) 
LLVM 11 with Pocl 1.6 - Dunkel provided version - Never unrolls (455 GB/s)
LLVM 11 with current master (5f806) (pre-1.7)- Self-compiled - Never unrolls (455 GB/s)

**Comment by isuruf** [comment]
dunkel provided version and current master both have https://github.com/pocl/pocl/pull/904 applied. Can you check if pocl-1.6 + that patch affects performance?

**Comment by nchristensen** [comment]
Yes, pocl-1.6 with that patch reliably produces the slower non-unrolled PTX.

**Comment by nchristensen** [comment]
Just adding https://github.com/pocl/pocl/pull/904/files#diff-a27fdae6cfdd7e96b10d693ff2b3708e3cb4d31da190458fc3af20bc733c7492R326-R340 to pocl-1.6 does not affect loop unrolling.

**Comment by isuruf** [comment]
> Yes, pocl-1.6 compiled with that branch merged

Can you tell me which commits you have tried that has bad performance?

Is the following correct?
c92a529205 has bad performance
1855f47a97 has good performance

**Comment by nchristensen** [comment]
I should have been clearing .cache; pyopencl was loading cached ptx/binaries. Clearing .cache between tests, I can confirm LLVM 9 unrolls and LLVM 11 does not unroll when running with the current master. Setting `cg.UnrollLoops` to true fixes the problem as does the version @isuruf suggested on the Pocl issue.

**Comment by inducer** [comment]
FYI: Setting the environment variable `PYOPENCL_NO_CACHE` to 1 should cause PyOpenCL to ignore its cache.

**Comment by inducer** [comment]
Since https://github.com/conda-forge/pocl-feedstock/pull/61 got merged into conda-forge's pocl, this should not be an issue any more. Closing. @nchristensen, please confirm when you have a minute and comment/reopen if it persists.

**Comment by nchristensen** [comment]
> Since [conda-forge/pocl-feedstock#61](https://github.com/conda-forge/pocl-feedstock/pull/61) got merged into conda-forge's pocl, this should not be an issue any more. Closing. @nchristensen, please confirm when you have a minute and comment/reopen if it persists.

Yes, the current pocl-cuda appears to unroll correctly.
