### ISSUE TITLE
Create CI integration

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/mirgecom#3]
These probably need to clone emirge, and then run the tests from there?

**Comment by majosm** [comment]
I think we should only run mirgecom's unit tests in this repo's CI (plus flake8 and whatever else, kind of like how it is in meshmode, etc.). I have a few unit tests that I'll be adding soon.

Also, I was kind of hoping certain others with more GitHub CI experience (*cough*) would come along and help set it up. :smile:

**Comment by matthiasdiener** [comment]
> (_cough_)

Hope it's not the virus 😄

> would come along and help set it up. 😄

More than happy to help 😄
