### ISSUE TITLE
TypeError: first_arg_dependent_memoize() got an unexpected keyword argument 'is_base_array'

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#302]
This affects CI as well as fresh installs.

E.g. https://github.com/inducer/meshmode/runs/2256445901

```
conda install 'decorator<5'
```
seems to serve as a workaround.

**Comment by inducer** [comment]
https://pypi.org/project/decorator/#history

![grafik](https://user-images.githubusercontent.com/352067/113455307-e9812380-93cf-11eb-9ce4-0c2b13714ee7.png)

Three withdrawn releases in ten hours. And 5.0.3 is still broken.

**Comment by inducer** [comment]
- https://github.com/micheles/decorator/issues/103
- https://github.com/micheles/decorator/issues/104

seem related.

**Comment by inducer** [comment]
If you're following along at home, this is affecting everything from pyopencl/pytools/pycuda upwards. I'm currently removing `decorator` from our dependencies, as they've impressively shown they cannot be trusted.

**Comment by bauman** [comment]
> they've impressively shown they cannot be trusted.

My stuff got bonked too, but I'll admit that was mostly my mistake for allowing my CI to happily pull a new Major version number knowing major versions are allowed to incorporate breaking changes.    

Like this thread, 4.4.2 and down seem fine so  `decorator<5`works. 

I should probably block major version upgrades across all the rest of my dependencies too.

**Comment by inducer** [comment]
> they've impressively shown they cannot be trusted.

Retrospectively, I'm sorry about having said that, particularly in public. @bauman Thanks for reminding me.

I was mad about having to go firefighting instead of doing something useful, but that doesn't excuse anything. Also, arguably, this was at least partially PyOpenCL's fault, since it was passing kwargs to a decorated function that didn't take any.

**Comment by inducer** [comment]
Also https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/53, which doesn't automatically back-link.

**Comment by micheles** [comment]
By all means, if you can avoid the dependency from the decorator module, you should avoid it! That is always good practice. I am known for studying the source of external dependencies, copying the 20 lines that I need and keep them in my code base rather than having an external dependency that can break at any moment. The decorator module is in a single file just for the benefit of users as anal as myself ;-) Having said that, if you show me what it the decorator that broke I can give some advice to fix it so that it works both with version 4 and 5 of the decorator module.

**Comment by inducer** [comment]
This should be mostly dealt with. I released new versions of pytools and pyopencl last night, and they got built and installed into the conda-forge archive overnight. I'll close once I've confirmed that CI is working  again.

**Comment by inducer** [comment]
@micheles, thanks for stopping by, and sorry again about what I said. My understanding (with a bit of distance) is that most of the CI failures that emerged were of the following nature: PyOpenCL contained this decorator:

https://github.com/inducer/pyopencl/blob/7a938c98dc510520bdf70c2e3c17649b95b32279/pyopencl/tools.py#L76-L77

used in this context:

https://github.com/inducer/pyopencl/blob/7a938c98dc510520bdf70c2e3c17649b95b32279/pyopencl/elementwise.py#L739-L741

being called like this:

https://github.com/inducer/pyopencl/blob/7a938c98dc510520bdf70c2e3c17649b95b32279/pyopencl/array.py#L935-L937

As you can see, the decorator doesn't allow kwargs, but the call site uses them. And `decorator` prior to version 5 must have *somehow* (?) made this OK, but in version 5, this was no longer the case. So, arguably, this is broken code, and it's probably good that it got taken care of.

**Comment by inducer** [comment]
Turns out there's one missing piece in grudge: https://github.com/inducer/grudge/pull/61

**Comment by inducer** [comment]
OK, the check marks are green again. I expect no further trouble as a result of this. If you observe something, open a new issue or comment here. Thanks for your patience!
