### ISSUE TITLE
Segfaults when running with more than 2 ranks

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#306]
I'm running into some segfaults with a fresh emirge checkout on my Mac when I try to run an example (say wave-eager-mpi) with more than 2 MPI ranks.

I looked into what specifically was triggering it, and it appears to be the `from mpi4py import MPI` line inside `mpi_entry_point`. I also noticed that if I comment out the `cl.get_platforms()` call above it, the segfault goes away.

The following script reproduces the issue for me:

```python
import pyopencl as cl
cl.get_platforms()

from mpi4py import MPI

print(f"{MPI.COMM_WORLD.Get_rank()=}")
```
If I run on 2 or fewer ranks, or comment out `cl.get_platforms()`, or move it after the `from mpi4py import MPI`, I stop getting segfaults.

Any ideas?

**Comment by inducer** [comment]
Do you have a `gdb` backtrace of the crash?

**Comment by majosm** [comment]
@inducer was able to figure out that this was caused by an hwloc version mismatch between pocl and mpi4py. Installing hwloc 1 via conda fixed the segfault.

```
$ conda install libhwloc=1
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.10.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /path/to/env

  added / updated specs:
    - libhwloc=1


The following packages will be DOWNGRADED:

  libhwloc                                 2.4.1-h9b1b92d_0 --> 1.11.13-hc10311c_0
  pocl                                       1.6-h25429ea_4 --> 1.6-hf61dbc3_4


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
