### ISSUE TITLE
Doc builds are failing

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#308]
https://readthedocs.org/projects/mirgecom/builds/13449703/

![grafik](https://user-images.githubusercontent.com/352067/113897413-74776a80-9790-11eb-824f-0c786d75869a.png)

Pretty strange, considering that this used to work. @matthiasdiener, could you take a look?

**Comment by matthiasdiener** [comment]
Fixed already? https://readthedocs.org/projects/mirgecom/builds/13450226/

**Comment by inducer** [comment]
Huh. Maybe it was on their end then. Thanks for taking a look!
