### ISSUE TITLE
Gmsh dependency breaks install @ LC

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#322]
As we discussed, this has the potential to break installs where gmsh cannot be installed by `pip`.  One platform where it *definitely* doesn't work at all is *Lassen* - because there are no compatible  packages for `gmsh` for that platform, and it fails to install using `pip`.   

One platform that is iffy is *Quartz* because as we've noted there it is required to be installed by `pip` and not `conda` in order to get a working install.  

The only platform that seems to be OK with `gmsh` installed via `pip` is the CI VM.

Any ideas on what to do about this?   CC: @inducer, @matthiasdiener

_Originally posted by @MTCam in https://github.com/illinois-ceesd/mirgecom/pull/213#discussion_r594475666_

**Comment by matthiasdiener** [comment]
gmsh should be available as a conda package on all our platforms. What is the Quartz error when installing it?
