### ISSUE TITLE
Remove MPI from example names

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#393]
Should we remove MPI from the example names?  Right now the "runner" script we have looks at the "-mpi" part of the example name to know that it is an MPI example, but shouldn't they all just be MPI examples?

**Comment by matthiasdiener** [comment]
I think we need at least one non-MPI example to help find MPI-specific bugs such as https://github.com/illinois-ceesd/mirgecom/pull/169.

**Comment by inducer** [comment]
Could always just use a grudge example for that...?

**Comment by majosm** [comment]
What about making MPI optional in the examples? Something like https://github.com/majosm/mirgecom/commit/c8838ee3fde3be5382a74d707d079ab92a61627d?

**Comment by MTCam** [comment]
> What about making MPI optional in the examples? Something like [majosm@c8838ee](https://github.com/majosm/mirgecom/commit/c8838ee3fde3be5382a74d707d079ab92a61627d)?

I like this, but can we not outright disable logging for the other ranks?  I would like it a lot better if we had a facility that automatically sends stdout only on rank 0, but that the user can force to come out otherwise if that's what they intended.

**Comment by matthiasdiener** [comment]
Done in #954
