### ISSUE TITLE
Remove stateful update in test_euler

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#401]
This here uses in-place modification, which means that this test won't work with lazy:

https://github.com/illinois-ceesd/mirgecom/blob/ecb7b885fd36ab12793e4fbe01bb1e7dc0becfdd/test/test_euler.py#L98-L102

**Comment by MTCam** [comment]
This code originally came from this grudge test:

https://github.com/inducer/grudge/blob/46d2fba2df22558fa476db38a31b446f1b40fbe4/test/test_trace_pair.py#L53

So.. just beware that if this is an issue it likely should be addressed there as well.

**Comment by inducer** [comment]
Thanks! https://github.com/inducer/grudge/pull/132

**Comment by MTCam** [comment]
> Thanks! [inducer/grudge#132](https://github.com/inducer/grudge/pull/132)

Thank you! Here's the corresponding fix (#413) in *MIRGE-Com*.
