### ISSUE TITLE
Production run timings have skyrocketed

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#406]
Production runs are now so expensive on Lassen that the timing batch jobs cannot complete within the system limits. 

The runs appear to hang for very long times doing this:
```
    return discr.project(cv_tpair.dd, "all_faces", flux_weak)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/grudge/grudge/eager.py", line 48, in project
    return op.project(self, src, tgt, vec)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/grudge/grudge/projection.py", line 68, in project
    return dcoll.connection_from_dds(src, tgt)(vec)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/meshmode/meshmode/discretization/connection/direct.py", line 350, in __call__
    return map_array_container(self, ary)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/arraycontext/arraycontext/container/traversal.py", line 174, in map_array_container
    return deserialize_container(ary, [
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/arraycontext/arraycontext/container/traversal.py", line 175, in <listcomp>
    (key, f(subary)) for key, subary in ser_ctr])
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/meshmode/meshmode/discretization/connection/direct.py", line 350, in __call__
    return map_array_container(self, ary)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/arraycontext/arraycontext/container/traversal.py", line 174, in map_array_container
    return deserialize_container(ary, [
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/arraycontext/arraycontext/container/traversal.py", line 175, in <listcomp>
    (key, f(subary)) for key, subary in ser_ctr])
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/meshmode/meshmode/discretization/connection/direct.py", line 360, in __call__
    return self._apply_with_inplace_updates(ary)
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/meshmode/meshmode/discretization/connection/direct.py", line 565, in _apply_with_inplace_updates
    actx.call_loopy(pick_knl(),
  File "/p/gpfs1/mtcampbe/CEESD/AutomatedTesting/MIRGE-Timing/timing/emirge/arraycontext/arraycontext/impl/pyopencl/__init__.py", line 184, in call_loopy
    wait_event_queue.pop(0).wait()
KeyboardInterrupt
```

Here is a link to the last working run's SQLITE file which should have all the package information:
https://github.com/illinois-ceesd/timing/blob/y1-production/nozzle_logs/nozzle_2021.06.26-01.12.52.sqlite

So far, Lassen is the only platform where this issue has been observed.  Both production cases appear to step normally on an intel macbook.

For the brave, until I can get a MWE going, the problem can be recreated on Lassen:
> cd <emirge_home>
> ./install.sh (your favorite arguments)
> cd mirgecom && git checkout y1-production
> git clone git@github.com:/illinois-ceesd/drivers_y1-nozzle y1-nozzle
> cd y1-nozzle/timing_run && git checkout y1-production
> (get a batch allocation)
> source <emirge_home>/config/activate_env.sh
> export PYOPENCL_CTX="port:tesla"
> jsrun -g 1 -a 1 -n 1 python -m mpi4py nozzle.py

This starts a serial (1 GPU) nozzle run. At this point, the code will hang up for an astounding amount of time when it is apparently stuck in the above (or similar) `discr.project` call.  

* For me (get a batch allocation) is: `lalloc 1 -q pdebug`

**Comment by inducer** [comment]
I'm having a bear of a time reproducing this.
* Could you provide instructions?
* Are you able to bisect which specific package is causing the issue?

FYI, this command in `runalyzer` will extract the `./version.sh` output from the sqlite in human-readable form:
```
print(eval(list(q("select emirge_package_versions from runs"))[0][0]).decode())
```

Running that on the file you linked gives me this: https://gist.github.com/inducer/c201078e1c822e9123bb3b4a1680c97b

**Comment by MTCam** [comment]
Sorry about that. I will try to narrow it down and answer some of this. So far, it appears we need a substantial number of points and to call `discr.project` with a CV object packing vector quantities (i.e. like fluxes).

**Comment by inducer** [comment]
https://github.com/illinois-ceesd/drivers_y1-nozzle/commit/3eb26b7fabf7f8b6e30a5fb2d28f0d45820b2d4a and https://github.com/illinois-ceesd/mirgecom/commit/9f464e07d5a578e7c5efbcdb512230ccb038effa seem out of sync: I get
```
Traceback (most recent call last):
  File "nozzle.py", line 728, in <module>
    main(restart_step=restart_step, restart_name=restart_name, user_input_file=input_file,
  File "/g/g92/andreask/emirge/mirgecom/mirgecom/mpi.py", line 154, in wrapped_func
    func(*args, **kwargs)
  File "nozzle.py", line 655, in main
    advance_state(rhs=my_rhs, timestepper=timestepper,
  File "/g/g92/andreask/emirge/mirgecom/mirgecom/steppers.py", line 293, in advance_state
    _advance_state_stepper_func(rhs=rhs, timestepper=timestepper,
  File "/g/g92/andreask/emirge/mirgecom/mirgecom/steppers.py", line 90, in _advance_state_stepper_func
    if dt < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
because `my_checkpoint` in `nozzle.py` is expected by `advance_state` to return `dt`, but it doesn't seem to.

**Comment by inducer** [comment]
Good news is I think I've reproduced the hang.

**Comment by MTCam** [comment]
> I'm having a bear of a time reproducing this.
>

Again, sorry about that @inducer.  It does seem to happen only at production scale atm, and on Lassen. I also could not reproduce it anywhere else.
 
> * Could you provide instructions? 

Added some in the description.

> * Does it happen on simpler cases than the y1 ones?

Don't have a MWE yet, will work on one next.

> * Is MPI required?

No; none of the current production problems are running MPI-parallel. 1 GPU only.

> * Are you able to diff your current `version.sh` output with the known-good one? 
> * Are you able to bisect which specific package is causing the issue?

I *could* diff them (I appreciate your `runalyzer` guidance!), but maybe won't need to now that we know...
030b2e7916e01406ccf618e38488c4cc07f1bcc5 (works fine)
9f69bd7b6c7568040a893b60958d6c2503dcd2d8 (works fine)
a348c936a58f68ec0458b952ac6146fcfb9c8da8 (takes longer than I can wait)
```
Author: Andreas Kloeckner <inform@tiker.net>
Date:   Sun Jun 27 00:19:21 2021 -0500

    Bring back meshmode PyOpenCLArrayContext with better transform logic
    
    Also adjust deprecation bits accordingly
```

This meshmode commit appears to be the culprit.

**Comment by MTCam** [comment]
> because `my_checkpoint` in `nozzle.py` is expected by `advance_state` to return `dt`, but it doesn't seem to.

This is exactly why the reproducing instructions indicate one should checkout `drivers_y1-nozzle@y1-production` - which includes the one-liner fix to `my_checkpoint`; `return dt`.

**Comment by inducer** [comment]
> This is exactly why the reproducing instructions indicate one should checkout `drivers_y1-nozzle@y1-production` - which includes the one-liner fix to `my_checkpoint`; `return dt`.

Ah! Missed that bit.

**Comment by MTCam** [comment]
> > This is exactly why the reproducing instructions indicate one should checkout `drivers_y1-nozzle@y1-production` - which includes the one-liner fix to `my_checkpoint`; `return dt`.
> 
> Ah! Missed that bit.

I just can't have you going around thinking the production problem is broken against y1-production! :)

**Comment by inducer** [comment]
I've got a workaround, and I've got the problem reasonably narrowed down, in part with your pointing to https://github.com/inducer/meshmode/commit/a348c936a58f68ec0458b952ac6146fcfb9c8da8 as a possible culprit:

Simply insert a `return None` before this line:

https://github.com/inducer/meshmode/blob/0f33e49cdad6f132cb00fa6e7a8f84851237d61b/meshmode/array_context.py#L55

**Comment by MTCam** [comment]
> Simply insert a `return None` 

Yep; it worked.

**Comment by inducer** [comment]
https://github.com/inducer/meshmode/pull/242 should fix it. :facepalm:
