### ISSUE TITLE
Add MPI example

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#41]
MPI-enabled version of [wave-eager.py](https://github.com/illinois-ceesd/mirgecom/blob/master/examples/wave-eager.py).

**Comment by matthiasdiener** [comment]
Wouldn't it be just a copy of this? https://github.com/inducer/grudge/blob/master/examples/wave/wave-eager-mpi.py

**Comment by majosm** [comment]
More or less. I was going to wait for the Euler stuff to come in and then see where we stand. This might not even be needed.

**Comment by MTCam** [comment]
It might be nice to drop-in wave-eager-mpi as a resident MPI example.  At this point, actual merge of Euler looks far off again.

**Comment by matthiasdiener** [comment]
Unless someone objects, I'll prepare a PR to merge wave-eager-mpi (I use it locally anyways already).

**Comment by MTCam** [comment]
Can we tweak it a little bit to use @majosm 's wave_operator and rk4 stepper?
