### ISSUE TITLE
Lingering production performance issues

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#412]
Related to #406, the applied fix appears to have fixed nozzle timings returning them to near pre-anomaly timings, but the flame case is still nearly 2x as expensive as it was last Friday.  It appears whatever changed happened on Saturday 06/26. 

Here's the plot indicating there is still some lingering issue:

<img width="929" alt="Screen Shot 2021-06-30 at 7 10 21 AM" src="https://user-images.githubusercontent.com/8116930/123958613-de0fab00-d972-11eb-94ed-38351f9d3f32.png">

We introduced DV memoization at `DVCache`, speeding up the case by a lot, but then the performance issue happened this weekend.  The flame timing run actually finished and produced data through the anomaly (#406) - but after the fix, did not come back all the way to its previous performance.

The data and SQL logs are here (respectively):
https://github.com/illinois-ceesd/timing/tree/y1-production/flame1d-timings.yaml
https://github.com/illinois-ceesd/timing/tree/y1-production/flame1d_logs

So far I have been *unsuccessful* at backing out the changes and recovering the previous performance.  I guess it could be possible that the issue is in some conda-installed package, too.

To run the flame case on Lassen:
> cd <emirge_home> && ./install.sh 
> cd mirgecom && git checkout y1-production
> git clone git@github.com:/MTCam/CEESD-Y1_Flame1D.git y1-flame-driver
> cd y1-flame-driver && git checkout y1-2  # adds needed (return dt) to main
> cd timing_run
> (get batch node)
> source <emirge_home>/config/activate_env.sh
> export PYOPENCL_CTX="port:tesla"
> jsrun -g 1 -a 1 -n 1 python -m mpi4py ./flame1d.sh

I'll be working on trying to narrow down the package/change that is causing the issue, but any help/hints would be deeply appreciated!

cc: @inducer

**Comment by MTCam** [comment]
Nevermind!   The different performance is due to the changes made to the driver itself.  The fuel and mechanism has been changed, and new boundary processing!   Backing these out recovers the pre-problem timings.

**Comment by inducer** [comment]
:relieved:
