### ISSUE TITLE
Issue when running Y0 on Quartz

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#57]
I am now consistently getting this error when running a coarse Y0 grid.  This worked last week.  Anyone have any ideas? @inducer? @matthiasdiener?
```
dlsym("/g/g17/mtcampbe/.cache/pocl/kcache/CB/AIPHNEHLMOKFBKELONKDOANEKJNJGHHAEMDBD/if_positive/128-1-1-goffs0/if_positive.so", "pocl_kernel_if_positive_workgroup") failed with '/g/g17/mtcampbe/.cache/pocl/kcache/GE/LMFFCEEAENGJFMGCDOELADCBHOLCNPMOMDPDA/resample_by_picking/16-1-1-goffs0/resample_by_picking.so: undefined symbol: pocl_kernel_if_positive_workgroup'.
note: missing symbols in the kernel binary might be reported as 'file not found' errors.
build program: kernel 'divide_r' was part of a lengthy cache retrieval (1.03 s)
building face restriction: start
srun: error: quartz19: task 0: Aborted (core dumped)
```

**Comment by matthiasdiener** [comment]
I guess you already tried removing the whole pocl cache? Are there multiple pocls installed on the system?

**Comment by MTCam** [comment]
I remove .cache/pocl, and that worked once.  The very next run, it is back.   This time I removed the entire .cache directory and it is currently running without crash.  Is there anything I can do to avoid it altogether?

**Comment by matthiasdiener** [comment]
Maybe try setting the XDG_CACHE_HOME env variable: https://github.com/illinois-ceesd/planning/issues/27

**Comment by inducer** [comment]
Agree with @matthiasdiener. Looks like all ranks are sharing the same cache directory. In addition to being slow for the reason @matthiasdiener points out, the synchronization may be imperfect in that the ranks trample over each others binaries.

**Comment by MTCam** [comment]
Is there a preferred method to handle this?   Should I just set it in the "srun" command as in @matthiasdiener's test?  Or should I absolutely prefer a node local solution?  This might be something we should consider in addition to #56

**Comment by matthiasdiener** [comment]
You can use the srun command with a /tmp folder as a completely node-local solution.

**Comment by MTCam** [comment]
Thanks a bunch guys!

**Comment by matthiasdiener** [comment]
Can this be closed?

**Comment by MTCam** [comment]
I haven't had this issue since your suggested fix.
