### ISSUE TITLE
Injector boundary shows large negative and > 1 mass fractions

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#613]
@anderson2981 reported this, here's a screenshot of the phenomenon:

![image](https://user-images.githubusercontent.com/352067/155176754-fed076e2-ddc1-4447-a8c1-60b01164dede.png)

@anderson2981, could you edit this to fill in the details (which case, when does it show up, ...)

cc @lukeolson @jbfreund

**Comment by MTCam** [comment]
Trying to piece together an easily reproduced example of the issue....

Here's a multi-species version of Poiseuille flow. It is set up to be like @anderson2981 's passive species injector runs.  It definitely produces "a" problem near the outflow - but I am not sure if it is a reproduction of "the" problem.

Code: https://github.com/illinois-ceesd/mirgecom/blob/production/examples/poiseuille-multispecies-mpi.py

Like the @anderson2981  injector case, this case starts to show bad mass fractions at some point near .2ms.   To reproduce, bump the `t_final` parameter beyond that which is needed to observe the issue.   Here's a snapshot (@ .1 ms) of the issue that this case produces before it gets too wild:

<img width="739" alt="Screen Shot 2022-02-25 at 8 26 52 AM" src="https://user-images.githubusercontent.com/8116930/155731827-ce430a7c-4f6a-4deb-9a36-47b51ff182dc.png">
 
The problem above is that the mass fraction Y has gone significantly negative, and also there should be no species "X" in that part of the domain at that time.  One feature that makes me skeptical that this is the exact phenomenon that @anderson2981  is observing in his runs is that I also see a problem in the density flow field in this same region:

<img width="337" alt="mass_closeup_outlet_poiseuille" src="https://user-images.githubusercontent.com/8116930/155732503-4f35931d-b90f-4be1-a8db-f519caafd44f.png">

@anderson2981 does not observe disturbances in the canonical conserved quantities for his runs.

**Comment by anderson2981** [comment]
Solved by fixing boundary condition implementation.
