### ISSUE TITLE
Add lazy symlinks for remaining examples?

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#693]
Some of the examples (autoignition, doublemach, hotplate, mixture, nsmix, poiseuille, sod) don't currently have `-lazy` symlinks for use with the CI example runner. Do we want to (/ can we) add them?

**Comment by MTCam** [comment]
We need to check.  Some of the examples do not/(did not used to) work with lazy until fusion array context.  I think if we want to add a lazy version of all the examples, maybe a better option would be to remove all the symlinks and just automatically run all the examples in both eager and lazy (maybe even lazy only!).

Possibly related #643
