### ISSUE TITLE
Initial Lassen GPU results

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/mirgecom#71]
## wave-eager-mpi

**wave-eager-mpi** run (1 node), with `write_vtk_file` commented out.

- https://github.com/illinois-ceesd/mirgecom/blob/f42a236c6496280f607d7ce1c6260158f3617e0d/examples/wave-eager-mpi.py
- 130050 elements, 76 time steps
- Memory usage: ~1.1 GByte

[large2.nvvp.zip](https://github.com/illinois-ceesd/mirgecom/files/5081609/large2.nvvp.zip)

GPU usage:
![image](https://user-images.githubusercontent.com/1772435/90347436-1c6bd800-dff6-11ea-89b0-92ba3c24503a.png)

- Total execution time:
  - CPU (1 rank): 152.79s
  - CPU (2 ranks): 102.81s
  - CPU (4 ranks): 68.57s
  - CPU (8 ranks): 52.93s
  - CPU (16 ranks): 44.65s
  - CPU (32 ranks): 124.13s
  - 1 GPU: 32.25s
  - 2 GPU: 29.91s
  - 4 GPU: 29.49s

- Memory bandwidth (1 GPU):
  `diff` kernel (kernel with highest bandwidth): 353.055 GByte/s (Volta max.: 900 GByte/s)

Profiling:

Function | # Calls | avg Time (ns) | avg Flops | avg Mem accesses | avg Bandwidth (GByte/s)
-- | -- | -- | -- | -- | --
nodes | 8 | 7843785 | 975375 | 4129087 | 0.526
actx_special_exp | 1 | 46163063 | 130050 | 2601000 | 0.056
resample_by_picking | 9240 | 4880 | 0 | 624240 | 127.911
diff | 926 | 88405 | 5202000 | 31212000 | 353.055
grudge_assign_0 | 1 | 50839772 | 1430550 | 16906500 | 0.333
actx_special_sqrt | 4 | 12156118 | 227587 | 2210850 | 0.182
grudge_assign_0 | 924 | 46447 | 780300 | 13005000 | 279.993
resample_by_mat | 2772 | 21833 | 1037680 | 3113040 | 142.582
diff | 6 | 10116170 | 2080800 | 6242400 | 0.617
grudge_assign_0 | 924 | 82408 | 390150 | 4681800 | 56.812
face_mass | 924 | 67820 | 3511350 | 18467100 | 272.295
grudge_assign_0 | 924 | 53431 | 260100 | 3901500 | 73.018
diff | 932 | 68782 | 2601000 | 15606000 | 226.891
grudge_assign_1 | 8 | 5308878 | 130050 | 3901500 | 0.735
grudge_assign_0 | 8 | 5240399 | 260100 | 3901500 | 0.745

![image](https://user-images.githubusercontent.com/1772435/90424357-9bf3b880-e083-11ea-89c7-d4677397f06c.png)

**Comment by matthiasdiener** [comment]
Initial results with y0_euler.py (1 node/1 GPU)


Function | # Calls | avg Time (ns) | avg Flops | avg Mem accesses | avg Bandwidth (GByte/s)
-- | -- | -- | -- | -- | --
nodes | 21 | 3802274 | 9299675 | 24411648 | 6.42
actx_special_sqrt | 1527 | 1173957 | 870325 | 5224616 | 4.45
actx_special_exp | 161 | 287601 | 6640 | 52479 | 0.182
flatten | 25 | 1703435 | 0 | 8137216 | 4.777
resample_by_picking | #### | 148005 | 0 | 1392979 | 9.412
diff | 1203 | 87075 | 24411648 | 73234944 | 841.053
grudge_assign_0 | 1 | 47006851 | 44754688 | 187155968 | 3.981
grudge_assign_0 | 1200 | 34477 | 15257280 | 85440768 | 2478.172
resample_by_mat | 4400 | 13041 | 1866716 | 4666791 | 357.854
diff | 15 | 6223488 | 19529318 | 48823296 | 7.845
grudge_assign_0 | 400 | 5119770 | 4068608 | 36617472 | 7.152
face_mass | 400 | 1573868 | 28480256 | 65097728 | 41.362
grudge_assign_0 | 400 | 1550552 | 2034304 | 12205824 | 7.872
diff | 400 | 1587637 | 8137216 | 24411648 | 15.376

**Comment by inducer** [comment]
That all looks very suspicious. :)

> 2.47 TB/s bandwidth

Good for us! Unfortunately, an integer factor above spec bandwidth

> [Tiny bandwidths everywhere else]

:exclamation: 

How big is the mesh?

Guessing from the number of bytes accessed by the nodes kernel (assuming order 4), much too small:
```
>>> 24411648 / 21/8/35/3
1383.8802721088434
```
(result is number of elements. 21 is number of calls, 8 is DP, 35 is number of DOFs in an order 4 tet, 3 is number of axes)

* Could you perhaps provide a (versioned!) link to the script that was run for the experiment?

**Comment by matthiasdiener** [comment]
> That all looks very suspicious. :)
> 
> > 2.47 TB/s bandwidth
> 
> Good for us! Unfortunately, an integer factor above spec bandwidth

Possible (at least in principle) due to caching effects.

> > [Tiny bandwidths everywhere else]
> 
> ❗
> 
> How big is the mesh?

The y0_euler.py prints "Total 3d elements: 1017152"

> 
> Guessing from the number of bytes accessed by the nodes kernel (assuming order 4), much too small:
> 
> ```
> >>> 24411648 / 21/8/35/3
> 1383.8802721088434
> ```
> 
> (result is number of elements. 21 is number of calls, 8 is DP, 35 is number of DOFs in an order 4 tet, 3 is number of axes)

Rechecking the profiling code, this column isn't actually GFlops/s, but GMemOps/s (values aren't scaled by the size of the memory access).

> * Could you perhaps provide a (versioned!) link to the script that was run for the experiment?

There is no script, just `python y0_euler.py`

**Comment by inducer** [comment]
> There is no script, just running python y0_euler.py

What I meant to ask was for you to provide a link of this form:

https://github.com/illinois-ceesd/mirgecom/blob/f42a236c6496280f607d7ce1c6260158f3617e0d/examples/y0_euler.py

Then
- I can just click to see the experiment
- It's clear which version you ran

> y0_euler.py prints "Total 3d elements: 1017152"

(nodes)

24411648/1017152=24.0

(so 24 accesses per element if we only count one call)

however

24411648/1017152/21=1.3

Maybe you're only reporting the last kernel?

Loopy can collect the number of footprint bytes and the number of accesses. Both are useful (as an upper and a lower bound on bandwidth, depending on factual cache behavior)

**Comment by matthiasdiener** [comment]
> > There is no script, just running python y0_euler.py
> 
> What I meant to ask was for you to provide a link of this form:
> 
> https://github.com/illinois-ceesd/mirgecom/blob/f42a236c6496280f607d7ce1c6260158f3617e0d/examples/y0_euler.py
> 
> Then
> 
> * I can just click to see the experiment
> * It's clear which version you ran


Good point, added.

> > y0_euler.py prints "Total 3d elements: 1017152"
> 
> (nodes)
> 
> 24411648/1017152=24.0
> 
> (so 24 accesses per element if we only count one call)
> 
> however
> 
> 24411648/1017152/21=1.3
> 
> Maybe you're only reporting the last kernel?

Not sure why you are dividing by the number of calls here.
The "avg mem accesses" column above is already per kernel call.

> 
> Loopy can collect the number of footprint bytes and the number of accesses. Both are useful (as an upper and a lower bound on bandwidth, depending on factual cache behavior)

Ok, I'll try finding those.

**Comment by inducer** [comment]
> Not sure why you are dividing by the number of calls here. The "avg mem accesses" column above is already per kernel call.

:facepalm: Thx!

**Comment by matthiasdiener** [comment]
I think I found out why the profiling values are strange: When running on the P9 Volta GPUs, the vast majority (>99%) of timing events from OpenCL return a time of '1'. This makes the time itself, but also the bandwidth results completely unreliable. This issue does not happen when running on the P9 CPU.

**Comment by inducer** [comment]
> the vast majority (>99%) of timing events returned by OpenCL return a time of '1' (ns).

Good observation! This would indeed explain a lot. Some thoughts:

- When you say "vast majority", what are the timings for the rest?
- Do you have profiling enabled on the queue?
- Does CUDA POCL give you valid profiling results on any other GPU? It sounds like that might just be timing the enqueue.
- Does the same happen with Nvidia CL?

**Comment by matthiasdiener** [comment]
> > It seems that only the first execution of each kernel gets a reasonable result.
> 
> Interesting. That's a good observation, and maybe something we can fix in pocl. Could you take a look?

This seems to work fine on porter (Nvidia-GPU) with pocl-cuda, so it seems to be an error specific to the P9 GPUs.

**Comment by inducer** [comment]
As discussed in the meeting, maybe a good next step is a simple reproducer (in C ideally) with the CUDA driver API that shows the timing anomaly. (See [`cuEventElapsedTime`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EVENT.html#group__CUDA__EVENT_1gdfb1178807353bbcaa9e245da497cf97)).

**Comment by inducer** [comment]
(FYI added some more tips on getting started to the comment above.)

**Comment by matthiasdiener** [comment]
Profiling works normally with a CUDA application on Lassen.

**Comment by inducer** [comment]
That's using the CUDA *runtime* API (`cuda` prefixes). POCL uses the CUDA *driver* API (`cu` prefixes).

**Comment by matthiasdiener** [comment]
Using the matrixmuldrv example indicated above does not show the timing error (see https://github.com/matthiasdiener/cuda-samples/commit/f1d446391db98bb0ad0902fcb30cd4957cbb6320)

**Comment by inducer** [comment]
I agree that that line could be relevant. If this happens repeatably (and it sounds that way from your description), it might be helpful to just print those timestamps and see what we get. Note that there's similar logic for the end time just below. And if the end times we get (before that `max` logic) are before the start times, then something is definitely off.

**Comment by matthiasdiener** [comment]
> Using the matrixmuldrv example indicated above does not show the timing error (see [matthiasdiener/cuda-samples@f1d4463](https://github.com/matthiasdiener/cuda-samples/commit/f1d446391db98bb0ad0902fcb30cd4957cbb6320))
> 
> Edit:
> Looking at the pocl code at https://github.com/pocl/pocl/blob/e66d74918f8fa79ee6e8864ed43faf17fb0493f7/lib/CL/devices/cuda/pocl-cuda.c#L1457, the `max(..., ... +1)` might be relevant.

Turns out that this actually seems to be the issue: https://github.com/pocl/pocl/pull/870
