### ISSUE TITLE
Unexpected performance 

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#72]
While attempting to evaluate the performance of the _mirgecom_ Euler module, I've been encountering some strange, and unexpected behaviors.  

The following data was collected on a single rank run of _mirgecom_ on Quartz.   It measures the time taken for Step 1 (which has overheads for kernel generation, caching, etc), and Step 9 (which has no such overheads).   As expected, Step 1 is much more expensive, but the tail-up at the end seems to indicate a ballooning of cost per grid element for larger grids.  All of the test grids fit well within the node memory.

![EulerStepTiming](https://user-images.githubusercontent.com/8116930/90775141-1871db80-e2be-11ea-8184-f63a4a6fad14.png)

What *is* apparent, and expected, for the above graph is that _mirgecom_ takes longer for larger grids and less time for smaller grids.  So I would expect that by partitioning the grid, for example into 2 pieces, that the time to complete a step would go down similar to the serial step cost above.  Instead we find the opposite.  More MPI ranks seem to cause the cost to go up:

![EulerStrongBoxLassen](https://user-images.githubusercontent.com/8116930/90778271-098d2800-e2c2-11ea-84fa-7ca14a2b5a7c.png)
 
The above data is a strong scaling behavior on Lassen.  I'll update this with the proper data from Quartz (i.e. a 1-to-1 comparison for the 2D scaling case used in the step timing).   This non-scaling MPI behavior is observed on Quartz and Lassen.

Trying to get to the bottom of this behavior, I used htop to watch resource consumption on the compute nodes running _mirgecom_.  Some observations from htop:
* _mirgecom_ single MPI rank spawns many threads on the node - fills it by default
*  _mirgecom_ is running 144 threads on each Quartz node - this is 4 * the number of physical cores available
* _mirgecom_ thread cpu utilization scales with grid size - larger grids show better utilization

<img width="894" alt="mirgecom_stepping_htop" src="https://user-images.githubusercontent.com/8116930/90779318-4a397100-e2c3-11ea-9f6e-df4f8c946cb5.png">
<img width="892" alt="Screen Shot 2020-08-15 at 8 42 40 AM" src="https://user-images.githubusercontent.com/8116930/90779467-7bb23c80-e2c3-11ea-940d-eb47644fb010.png">
<img width="892" alt="Screen Shot 2020-08-15 at 8 42 53 AM" src="https://user-images.githubusercontent.com/8116930/90779494-8371e100-e2c3-11ea-8a7f-6cf5878db484.png">

**Comment by inducer** [comment]
* Let's keep the single-node and distributed parts of this separate. I propose we use this issue to discuss the single-node case.
* The increase at the end could very well be a cache effect, which is not entirely unexpected. (Do we expect to run inside or outside of L2? I would hope outside, but I'm not sure... especially given the number of cores.)
* Exactly how caches interact with memory pools is not fully clear to me. However, this might matter less in a fully fused version of the operator (fewer allocations!) than in the current, fine-grained one.
* POCL and work item/processor affinity is a bit of an unsolved problem (https://github.com/pocl/pocl/issues/330) that just celebrated its four-year anniversary.

**Comment by inducer** [comment]
@MTCam Could you describe/provide a script to reproduce the measurement above?

**Comment by MTCam** [comment]
> @MTCam Could you describe/provide a script to reproduce the measurement above?

Hi please have a look at [this script](https://github.com/illinois-ceesd/mirgecom/blob/y0euler/examples/run_grid_scale.sh) that runs within a batch environment to produce the profiles.   It runs [this acoustic pulse example/test](https://github.com/illinois-ceesd/mirgecom/blob/y0euler/examples/pulse-scale-mpi.py).

**Comment by inducer** [comment]
(Please use versioned links. Hit y before copying the URL.)

**Comment by inducer** [comment]
https://github.com/inducer/grudge/pull/23 was just merged, which removes a healthy amount of CPU/GPU synchronization in DG operator evaluation, which could improve these results.

**Comment by inducer** [comment]
This is ancient, and I believe it pertains to eager. I'll close it. Scream if you object.
