### ISSUE TITLE
Mirgecompare with different rank numbers

### ISSUE THREAD

**Issue by poulNA** [illinois-ceesd/mirgecom#725]
### **Current Behavior**

Files: fld-wave-mpi-000-0000.pvtu, fld-wave-mpi-001-0000.pvtu, fld-wave-mpi-000-0010.pvtu, fld-wave-mpi-001-0010.pvtu
- files with 000 are rank 0
- files with 001 are rank 1
- files from 1rank are by mpirun -n 1
- files from 2rank are by mpirun -n 2
- 0000 and 0010 determine the time step

### Testing Rank 0 and Rank 1 with 0010 file from mpirun -n 1 and mpirun-n 2
-Command bin/mirgecompare.py 1rank/fld-wave-mpi-000-0010.pvtu 2rank/fld-wave-mpi-000-0010.pvtu
-Result
Field: u Max Error: 0.2766170290596787
Field: v Max Error: 0.351590918396429
ValueError: Fidelity test failed: Mismatched data array values tolerance=1e-12.

### Testing Rank 0 and Rank 1 with 0010 file from mpirun -n 2
-Command bin/mirgecompare.py 2rank/fld-wave-mpi-000-0010.pvtu 2rank/fld-wave-mpi-001-0010.pvtu
-Result
Field: u Max Error: 0.2766170290596787
Field: v Max Error: 0.351590918396429
ValueError: Fidelity test failed: Mismatched data array values tolerance=1e-12.

### Testing Rank 0 and Rank 1 with 0000 file from mpirun -n 2
-Command bin/mirgecompare.py 2rank/fld-wave-mpi-000-0000.pvtu 2rank/fld-wave-mpi-001-0000.pvtu
-Result
Field: u Max Error: 0.96754678098049
Field: v Max Error: 0
ValueError: Fidelity test failed: Mismatched data array values tolerance=1e-12.

**Comment by MTCam** [comment]
This is not an issue as far as I can tell.  Can you explain the test and your expected outcome?

**Comment by matthiasdiener** [comment]
> This is not an issue as far as I can tell. Can you explain the test and your expected outcome?

This is related to https://github.com/annabellej/mirgecompare/issues/17. Our goal here is to at least warn users when they are trying to compare output files from runs with different numbers of ranks, in particular for this test that Paul ran:

```
Testing Rank 0 and Rank 1 with 0010 file from mpirun -n 1 and mpirun-n 2
-Command bin/mirgecompare.py 1rank/fld-wave-mpi-000-0010.pvtu 2rank/fld-wave-mpi-000-0010.pvtu
-Result
Field: u Max Error: 0.2766170290596787
Field: v Max Error: 0.351590918396429
ValueError: Fidelity test failed: Mismatched data array values tolerance=1e-12.
```

**Comment by MTCam** [comment]
> > This is not an issue as far as I can tell. Can you explain the test and your expected outcome?
> 
> This is related to [annabellej/mirgecompare#17](https://github.com/annabellej/mirgecompare/issues/17). Our goal here is to at least warn users when they are trying to compare output files from runs with different numbers of ranks, in particular for this test that Paul ran:
> 
> ```
> Testing Rank 0 and Rank 1 with 0010 file from mpirun -n 1 and mpirun-n 2
> -Command bin/mirgecompare.py 1rank/fld-wave-mpi-000-0010.pvtu 2rank/fld-wave-mpi-000-0010.pvtu

The fidelity test should not pass in this case AFAICT.  Rank 0 on a serial run should not match Rank 0 in a parallel run.  The two have differently-sized meshes.

**Comment by matthiasdiener** [comment]
> The fidelity test should not pass in this case AFAICT. Rank 0 on a serial run should not match Rank 0 in a parallel run. The two have differently-sized meshes.

Oh, I see. Is there an example we can run that maintains the same mesh size overall, or do we just adjust the mesh size between different runs?

**Comment by MTCam** [comment]
> > The fidelity test should not pass in this case AFAICT. Rank 0 on a serial run should not match Rank 0 in a parallel run. The two have differently-sized meshes.
> 
> Oh, I see. Is there an example we can run that maintains the same mesh size overall, or do we just adjust the mesh size between different runs?

We don't change the mesh in-between runs; we just partition it.  In the serial run, rank 0 has the _entire_ mesh in one output file.   In the parallel run, each rank's output file only has a portion of the mesh, so these two files cannot agree.   One thing we _could_ do is assemble the data back together by stitching together the multiple output files in the parallel runs.  I am unsure what data the files have about the inter-partition connectivity.  We need to read or create the inter-{partition, cell} connectivity to re-assemble the data.

**Comment by matthiasdiener** [comment]
> Edit: for now, probably the safest thing to do is toss an error if two runs of differing NRANK are compared. The PVTU files will reference a number of files = the number of ranks, so that might be an easy way to detect if the two runs have different NRANKS. 

Yeah, this was what we had in mind for now, but throwing a warning instead of an error since we have to parse the XML ourselves, without vtk, since the vtk API for number of files does not appear to work correctly :-/

**Comment by matthiasdiener** [comment]
Done in #727.
