### ISSUE TITLE
Lazy fails under kaushikcfd/loopy

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#791]
*MIRGE-Com* recent CI failures (https://github.com/illinois-ceesd/mirgecom/actions/runs/3373950600/jobs/5615521293#step:4:481) are coming from some issue with kaushikcfd/loopy, presumably after changes in conda forge packages or underlying Python version.   Backing out to inducer/loopy (https://github.com/illinois-ceesd/mirgecom/pull/790) fixes the issue with lazy eval - but kaushikcfd/loopy is required for lazy eval with mixtures.

Reproduce this (apparently on any platform) by installing a fresh mirgecom@main and running `pytest -x test_lazy.py`. 

@matthiasdiener has suggested `pip install pyrsistent==0.18.1` may fix this. 
✅ Update:  downgrading `pyrsistent` does indeed fix the issue.

**Comment by matthiasdiener** [comment]
With https://github.com/kaushikcfd/loopy/pull/2 merged, this should work now again out of the box.

**Comment by MTCam** [comment]
Many thanks, y'all!
