### ISSUE TITLE
[CI] No sudo on porter

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/mirgecom#792]
Every time the porter CI runs, I get spammed with this:
```
Github Actions CI runner <githubrunner@porter.cs.illinois.edu> (Yest. 20:22) (archived unread)
Subject: *** SECURITY information for porter.cs.illinois.edu ***
To: root@porter.cs.illinois.edu
Date: Thu, 03 Nov 2022 14:22:13 -0500

porter.cs.illinois.edu : Nov  3 14:22:13 : githubrunner : user NOT in sudoers ;
PWD=/home/githubrunner/actions-runner/_work/mirgecom/mirgecom ; USER=root ; COMMAND=/usr/bin/apt-get update
```
The runner is *not* allowed to run sudo anything, nor should it try to. @matthiasdiener Could you please get that fixed?

**Comment by inducer** [comment]
Thanks for working on a fix. Unfortunately, that doesn't seem to have fixed the entirety of it. Just got another:
```
Github Actions CI runner <githubrunner@porter.cs.illinois.edu> (Today 08:06) (inbox unread)
Subject: *** SECURITY information for porter.cs.illinois.edu ***
To: root@porter.cs.illinois.edu
Date: Mon, 07 Nov 2022 08:06:21 -0600

porter.cs.illinois.edu : Nov  7 08:06:21 : githubrunner : user NOT in sudoers ; PWD=/home/githubrunner/actions-runner/_work/mirgecom/mirgecom ; USER=root ; COMMAND=/usr/bin/apt-get
update
```

**Comment by MTCam** [comment]
> Thanks for working on a fix. Unfortunately, that doesn't seem to have fixed the entirety of it. Just got another:

My bad.  I hadn't merged the fix up into production.  Should be all fixed up now (with production, at least).   Any development in PR that has not merged main will obviously still trigger this message.

**Comment by inducer** [comment]
Ah, not a problem. Thanks for explaining.
