### ISSUE TITLE
Remove "Remove grudge dependence?"?

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#8]
Inspired by a comment in the Euler pull request...

When I created the mirgecom repo I added comments around any grudge code I saw ([example](https://github.com/illinois-ceesd/mirgecom/blob/966506aa3f7e5eed5a49b52b9199b0665061b872/mirgecom/wave.py#L29)), thinking we might rip that stuff out and put it in mirgecom instead of carrying grudge around as a permanent dependency. If that's still a possibility (assuming it ever was...?), I'll leave the comments in, otherwise I should probably remove them to avoid confusion. Thoughts?

**Comment by inducer** [comment]
While it's totally possible (and not particularly hard) to build a viable DG solver on top of just meshmode, grudge does bring a few things that are worth having IMO, such as dimension independence, overintegration, and some helpers for distributed-memory). I think we'll substantially remodel it (and perhaps move some of the purely DG-focused things "down" into it from mirgecom), I do see it having a role to play going forward.
